[package]
name = "FolderDeleteBySize"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/nhockey/FolderDeleteBySize"
license = "MIT AND BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"