[package]
name = "FolderDeleteBySize"
<<<<<<< HEAD
version = "0.2.3"
||||||| parent of 3d8d3b8 (Changed Cargo.toml)
version = "0.2.0"
=======
version = "0.2.1"
>>>>>>> 3d8d3b8 (Changed Cargo.toml)
edition = "2021"
<<<<<<< HEAD
repository = "https://github.com/nhockey/FolderDeleteBySize"
license = "MIT AND BSD-2-Clause"
||||||| parent of 3d8d3b8 (Changed Cargo.toml)

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
=======
repository = "https://github.com/nhockey/FolderDeleteBySize"
license = "MIT AND BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
>>>>>>> 3d8d3b8 (Changed Cargo.toml)

[dependencies]
fs_extra = "^1.3"
