[package]
name = "FolderDeleteBySize"
version = "0.2.2"
edition = "2021"
repository = "https://github.com/nhockey/FolderDeleteBySize"
license = "MIT AND BSD-2-Clause"

[dependencies]
fs_extra = "1.2.0"